version: '3'
services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html/public
    ports:
      - 9005:80

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Diaediaediae123
      MYSQL_DATABASE: homeland
      MYSQL_USER: diae
      MYSQL_PASSWORD: Diaediaediae123
    ports:
      - 3305:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9015:80
    environment:
      - PMA_ARBITRARY=1